### ISSUE TITLE
Requests hanging there

### ISSUE THREAD

**Issue by alex88** [julianbrowne/graffeine#1]
Hello, I'm running neo4j 1.9.2 on OSX, I've installed graffeine with both npm and git clone, then I run it via npm start or node server and it seems to start fine.

Trying to connect with browser instead keeps in waiting state and never returns any data.

Any idea?

**Comment by coolxeo** [comment]
Same for me, I'm on ubuntu 13.10

**Comment by marzagao** [comment]
Hullo, I had the same issue until I realized I had a version of node.js (v0.10.25) different than the one specified in the Graffeine readme doc (v0.8.25). I downgraded to that version and it worked. You could also try using the node version manager (nvm - https://github.com/creationix/nvm) to install that older version, if you need to keep multiple versions of node installed.

**Comment by julianbrowne** [comment]
Yes. Sorry for taking an age to reply to this. The file handler for node-static needed an update for later versions of node (same as this issue: https://github.com/cloudhead/node-static/issues/89). Pushed a new version that should fix this.
